image: maven:3-jdk-8-alpine

# ---------------------------------------
# Global
# ---------------------------------------

stages:
  - build
  - test
  - deploy

# ----------------------------------------
# Build
# ----------------------------------------

build:
  stage: build
  script:
    - sh build/build.sh
  artifacts:
    paths:
      - src/target/
    expire_in: 1 hour

# ----------------------------------------
# Tests
# ----------------------------------------

test:
  stage: test
  script:
    - sh tests/tests.sh
  artifacts:
    paths:
      - src/target/
    expire_in: 1 hour

# ----------------------------------------
# Deploy
# ----------------------------------------

deploy:
  stage: deploy
  script:
    - cd src/
    - mvn package
    - mvn javadoc:javadoc
    - mv target/site/apidocs docs/
    - mv target/*.jar jotto.jar
  only: 
    - master
  artifacts:
    paths:
      - src/jotto.jar
      - src/resources/*
      - src/docs/
    expire_in: 4 weeks