image: maven:3-jdk-8-alpine

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - sh build/build.sh
  artifacts:
    paths:
      - jotto/target/
    expire_in: 1 hour

test:
  stage: test
  script:
    - sh tests/tests.sh
  artifacts:
    paths:
      - jotto/target/
    expire_in: 1 hour

deploy:
  stage: deploy
  script:
    - cd jotto/
    - mvn package
    - mvn javadoc:javadoc
    - mv target/*.jar jotto.jar
  only: 
    - master
  artifacts:
    paths:
      - jotto/jotto.jar
      - jotto/resources/*
      - jotto/doc/
    expire_in: 4 weeks